services:
  - type: web
    name: reportgen
    runtime: docker
    dockerfilePath: ./portable-app/Dockerfile
    dockerContext: ./portable-app
    plan: free
    envVars:
      - key: PORT
        value: 8080

